[buildPlans.NeonMono]
family = "NeonMono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.NeonMono.variants]
  inherits = "ss14"

    [buildPlans.NeonMono.variants.design]
    zero = "tall-slashed"
    dollar = "interrupted"
    cent = "bar-interrupted"
    lig-ltgteq = "flat"

[buildPlans.NeonMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.NeonMono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.NeonMono.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.NeonMono.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.NeonMono.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.NeonMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.NeonMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.NeonMono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
